# Generated by Django 2.1.1 on 2019-01-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('headquarters', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Maths')], max_length=4, verbose_name='Subjects')),
                ('language', models.CharField(choices=[('HIN', 'Hindi'), ('ENG', 'English')], max_length=3, verbose_name='Language')),
            ],
        ),
    ]
