# Generated by Django 2.1.5 on 2019-01-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('headquarters', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_type', models.CharField(choices=[('11th', '11th'), ('12th', '12th'), ('13th', '13th')], max_length=10, verbose_name='standard type')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Maths'), ('BIOL', 'Biology')], max_length=20, verbose_name='Subjects')),
                ('language', models.CharField(choices=[('HIN', 'Hindi'), ('ENG', 'English')], max_length=20, verbose_name='Language')),
            ],
        ),
    ]
