# Generated by Django 2.1.5 on 2019-01-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_type', models.CharField(choices=[('11th', '11th'), ('12th', '12th'), ('13th', '13th')], max_length=10)),
            ],
        ),
    ]
