# Generated by Django 2.1.1 on 2019-01-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('P1', 'Phase 1'), ('P2', 'Phase 2'), ('P3', 'Phase 3')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
