# Generated by Django 2.1.5 on 2019-01-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standards',
            name='standard_type',
            field=models.CharField(choices=[('11th', '11th'), ('12th', '12th'), ('13th', '13th')], max_length=10, verbose_name='standard type'),
        ),
    ]
