# Generated by Django 2.1.1 on 2019-01-24 19:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20190125_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Dpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Data')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Phase')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Standards')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, size=None)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Data')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Phase')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Standards')),
            ],
        ),
        migrations.AddField(
            model_name='booklet',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Data'),
        ),
        migrations.AddField(
            model_name='booklet',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Phase'),
        ),
        migrations.AddField(
            model_name='booklet',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Standards'),
        ),
        migrations.AddField(
            model_name='booklet',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subjects'),
        ),
    ]
